docker:
  image: ${oc.env:DARKNET_DOCKER_IMAGE,darknet}
  gpu_id: 0

training:
  data_dir: ${data_dir}/mnist
  size: 416
  batch: 64
  subdivisions: 8
  n_classes: 1
  max_batches: 20000
  pretrained: ${original_work_dir}/data/yolo/yolov4.conv.137
  cfg: ${original_work_dir}/data/yolo/yolov4.cfg.template

config: ""
weights: null
