docker:
  image: ${oc.env:DARKNET_DOCKER_IMAGE}
  gpu_id: 0

training:
  size: 416
  batch: 64
  subdivisions: 8
  n_classes: 1
  max_batches: 100000
  pretrained: ${original_work_dir}/data/yolo/yolov4.conv.137
  cfg: ${original_work_dir}/data/yolo/yolov4.cfg.template
