stages:
  extract:
    foreach:
      - mnist
      - dsprites
      - multiscalemnist
    do:
      cmd: mkdir data/${item} && tar -xzvf data/${item}.tar.gz -C data/${item}
      deps:
        - data/${item}.tar.gz
      always_changed: true
