stages:
  extract:
    foreach:
      - mnist
      - dsprites
      - multiscalemnist
      - coco
      - coco_small
      - movi_a
      - movi_b
      - movi_c
      - movi_d
      - movi_e
    do:
      cmd: mkdir data/${item} && tar -xzvf data/${item}.tar.gz -C data/${item}
      deps:
        - data/${item}.tar.gz
      always_changed: true
