_target_: NULL

learning_rate: 1e-4

z_present_threshold: 0.2
z_present_p_prior: 0.1

reconstruction_coef: 5
what_coef: 0.1
depth_coef: 0.1
present_coef: 0.1
objects_coef: 10

reset_non_present: false
negative_percentage: 0.0
max_objects: NULL
