defaults:
  - default.yaml

_target_: src.models.dir_module.DIR

encoder:
  yolo:
    - ${darknet.config}
    - ${darknet.weights}

  z_what_size: 32
  z_what_hidden: 3
  z_what_scale_const: 0
  z_depth_scale_const: 0

  train_backbone: false
  train_neck: false
  train_head: false
  train_what: true
  train_depth: true

  clone_backbone: neck

  filter_classes: NULL

  nms_threshold: 0.45
  nms_always: false

decoder:
  z_what_size: ${model.encoder.z_what_size}
  decoded_size: 32
  decoder_channels: 32
  square_boxes: false
  image_size: ${darknet.training.size}
  train_what: true
  include_negative: false
  use_render: false
