_target_: src.models.dir_module.DIR

learning_rate: 1e-4

z_present_threshold: 0.2
z_present_p_prior: 0.1

reconstruction_coef: 5
what_coef: 0.1
depth_coef: 0.1
present_coef: 0.1
objects_coef: 10

normalize_reconstructions: true
reset_non_present: true

encoder:
  _target_: src.models.components.encode.encoder.Encoder

  yolo_cfg_file: ${darknet.config}
  yolo_weights_file: ${darknet.weights}

  z_what_size: 32
  z_what_hidden: 3
  z_what_scale_const: 0
  z_depth_scale_const: 0

  train_backbone: false
  train_neck: false
  train_head: false
  train_what: true
  train_depth: true

  clone_backbone: neck

decoder:
  _target_: src.models.components.decode.decoder.Decoder

  z_what_size: ${model.encoder.z_what_size}
  decoded_size: 32
  image_size: ${darknet.training.size}
  train_what: true
