_target_: src.models.rdir_module.RDIR

dir:
  _target_: src.models.dir_module.DIR.load_from_checkpoint
  checkpoint_path: ""

  learning_rate: 1e-4

  z_present_threshold: 0.2
  z_present_p_prior: 0.1

  reconstruction_coef: 5
  what_coef: 0.1
  depth_coef: 0.1
  present_coef: 0.1
  objects_coef: 10

  normalize_reconstructions: true
  reset_non_present: false
  negative_percentage: 0.2

n_rnn_hidden: 2
rnn_kernel_size: 5
rnn_cls:
  _partial_: true
  _target_: torch.nn.GRU
n_rnn_cells: 2
rnn_bidirectional: true

train_backbone: false
train_neck: false
train_head: false
train_what: true
train_depth: true
train_rnn: true
