_target_: src.models.dir_sequential_module.DIRSequential

learning_rate: 1e-4

dir: data/dir/mnist-dir-tiny-deterministic.ckpt
seq_rnn_cls:
  _target_: torch.nn.GRU
  _partial_: True
seq_n_layers: 1
seq_bidirectional: False
train_encoder_backbone: False
train_encoder_neck: False
train_encoder_head: False
train_encoder_what: False
train_encoder_depth: False
train_decoder_what: True
