_target_: src.datamodules.yolo.YOLODataModule

data_dir: ${darknet.training.data_dir}
config_path: ${darknet.config}
batch_size: 2
num_workers: 0
image_size: ${darknet.training.size}
pin_memory: true
